src/main/java/ru/org/linux/auth/AuthenticationEntryPointImpl.java
src/main/java/ru/org/linux/auth/PasswordEncoderImpl.java
src/main/java/ru/org/linux/auth/SecurityFilter.java
src/main/java/ru/org/linux/auth/UserDetailsImpl.java
src/main/java/ru/org/linux/auth/UserDetailsServiceImpl.java
src/main/java/ru/org/linux/poll/PreparedPollVariantResult.java
src/main/java/ru/org/linux/site/HTTPErrorController.java

опять коммент лишний и ненужный

---

pom.xml

Scala 2.11.5

---

src/main/webapp/WEB-INF/jsp/server.jsp

Мелочь, а фаллаут всё-таки выглядит кривовато.

/about: единый вид для обоих списков

---

src/main/java/ru/org/linux/tracker/TrackerApiController.java

По адресу ```/api/tracker/?offset=OFFSET&filter=FILTER```
```
{
"trackerItems" : [ {
"id" : 1948680,
"url" : "/forum/general/1948656?lastmod=1433497629741",
"title" : "systemd установлен на миллионе персональных компьютеров",
"groupTitle" : "General",
"postDate" : "2015-06-05T09:47:09.741+0000",
"lastModified" : "2015-06-05T09:47:09.741+0000",
"lastCommentedBy" : "maxcom",
"pages" : 1,
"tags" : [ "systemd", "никто не читает теги", "статистика" ],
"author" : "maxcom"
} ]
}
```
В случае ошибки
```JSON
{
"error" : "Некорректное значение offset"
}
```

API: Получение последних сообщений трекера

---

src/main/java/ru/org/linux/user/ScoreUpdater.java

https://www.linux.org.ru/forum/linux-org-ru/11696904

ИСПРАВИЛ НАЧИСЛЕНИЕ СКОРА

---

src/main/webapp/WEB-INF/jsp/activate.jsp

Revert "небольше исправление кода activate.jsp, по логике сделал"

---

src/main/resources/es-mapping.json

https://www.linux.org.ru/forum/linux-org-ru/11731497

search: remove author field from _all

---

pom.xml

даже в опенбсд его обновили...

up elasticsearch

---

pom.xml

Revert "обновил liquibase"

---

pom.xml
sql/updates/2012-09-18-user-of-usercomments-table.xml

не работает 2015-10-29-drop-jamwiki со старой версией, не умеет каскадное удаление

liquibase update for correct run updates/2015-10-29-drop-jamwiki.xml

---

src/main/webapp/sass/_fontello.scss

https://www.linux.org.ru/forum/lor-source/12029950

bugfix fontello icon-tag for google-chrome/chromium

---

src/main/java/ru/org/linux/user/RegisterRequestValidator.java

[очередная однодневка.](http://one-time.email)

внёс one-time.email в список плохих адресов

---

pom.xml
src/main/webapp/WEB-INF/jsp/server.jsp

даже в портах опенбсд обновили, лол

activemq 5.13

---

src/main/webapp/WEB-INF/jsp/footer-main.jsp

По мотивам https://www.linux.org.ru/forum/lor-source/12244869

up to 2016

---

src/main/webapp/WEB-INF/tags/poll.tag

https://www.linux.org.ru/polls/polls/12633058?cid=12637585

Fix whitespace in poll results.

---

src/main/java/ru/org/linux/user/User.java

Скор корректора приводим к rules.md

---

src/main/webapp/WEB-INF/jsp/footer-main.jsp

Год петуха

---

pom.xml

elasticsearch 5.1.2

---

src/main/webapp/WEB-INF/tags/message.tag

https://www.linux.org.ru/forum/linux-org-ru/13145064

fix 13145064

---

src/main/webapp/WEB-INF/jsp/group.jsp
src/main/webapp/WEB-INF/jsp/view-message.jsp
src/main/webapp/WEB-INF/tags/message.tag

rss-подписка таки с дефисом...

заменил дефис на тире

---

src/main/java/ru/org/linux/comment/CommentService.java
src/main/java/ru/org/linux/topic/TopicService.java
src/main/scala/ru/org/linux/user/UserService.scala
src/test/scala/ru/org/linux/topic/TopicDaoIntegrationTest.scala

Исправил появление уведомления о касте от игнорируемого пользователя.

Исправление уведомления о касте от игнорируемого пользователя

---

pom.xml

обновил зависимости-с

---

sql/updates/2017-11-13-force-unlogin.xml
src/main/java/ru/org/linux/auth/GenerationBasedTokenRememberMeServices.java
src/main/java/ru/org/linux/auth/LoginController.java
src/main/java/ru/org/linux/user/UserDao.java
src/main/webapp/WEB-INF/jsp/whois.jsp
src/main/webapp/WEB-INF/springapp-security.xml

Добавляет кнопку завершения всех сессий (рядом с обычной кнопкой выхода).

Кнопка «выйти со всех устройств»

---

src/main/java/ru/org/linux/spring/SameIPController.java
src/main/webapp/WEB-INF/jsp/sameip.jsp

Now sameip.jsp shows comments for 3 days

---

src/main/webapp/WEB-INF/jsp/edit.jsp

Remove mini-news checkbox when editing poll

---

src/main/java/ru/org/linux/util/formatter/ToHtmlFormatter.java

Ссылки будут выглядеть так: 
```
<a href="..."><span><img alt="LOR:" src="/img/tuxlor.png"/>&nbsp;НАЗВАНИЕ ТЕМЫ</span></a>
```
[](https://i.imgur.com/zUpDJkf.png)

fixed issue #809 in upstream

---

src/main/webapp/js/lor.js

This fixes commit c92274db3da2ee9ccdb2b95d8d81ec4d95daf457

Fix: подмена адресной строки не работала на страницах кроме первой

---

src/main/webapp/js/lor.js

https://www.linux.org.ru/forum/lor-source/14805130
This fixes commit c92274db3da2ee9ccdb2b95d8d81ec4d95daf457

Fixing possible race conditioin in replace_state() function

---

src/main/webapp/js/lor.js

https://www.linux.org.ru/forum/general/14841331
Issue introduced in 240f08de10b7b7ef24f9d9483534de549096bc2f

lor.js: prevent looping in replace_state().

---

src/main/java/ru/org/linux/user/DeregisterController.java
src/main/webapp/WEB-INF/jsp/edit-profile.jsp

Disallow account deletion for users with score < 100

---

sql/updates/2019-05-12-grant-deleted.xml
src/main/java/ru/org/linux/user/UserDao.java

Remove edit history after account deletion

---

src/main/java/ru/org/linux/topic/TopicDao.java
src/main/java/ru/org/linux/user/DeregisterController.java
src/main/scala/ru/org/linux/search/ElasticsearchIndexService.scala

Reindex topics after account deletion

---

src/main/webapp/sass/white2/style.scss

тема white2, убран белый фон на главной странице в блоке новостей на строке с кол-вом комментариев
см.  www.linux.org.ru/forum/linux-org-ru/15307481

White2 css fix 

---

src/main/webapp/sass/_common.scss

фикс вот этого: https://github.com/maxcom/lorsource/issues/888

fix issue 888

---

src/main/webapp/sass/tango/_style.scss
src/main/webapp/sass/tango/_tango-dark.scss

Additional information: https://www.linux.org.ru/forum/linux-org-ru/16174343
Было:
Стало:

Improve blockquote colors on the Tango skin

---

src/main/webapp/qrerror/502.html

Тут нет противопоставления -> не с прилагательным пишется слитно.

Update 502.html: typo fix

---

docker/Dockerfile

The Java version has been updated to 17.

Fix Dockerfile for local development

---

src/main/scala/ru/org/linux/reaction/ReactionService.scala

emoji "два чая этому господину!"

---

src/main/webapp/WEB-INF/jsp/tracker-new.jsp
src/main/webapp/WEB-INF/jsp/view-topic.jsp

Наверное, стоит и по другим страницам пройтись и также поправить ссылки. 
Могу доделать потом следующим ПРом.

Добавил rel для ссылок на следующую и предыдущую страницы при просмотре темы и на Трекере.
